#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# setup.sh – First-time setup wizard for Safe Agentic AI
# ─────────────────────────────────────────────────────────────────────────────
# Detects your platform, asks a few questions, generates .env
# Run once before opening in VS Code Dev Containers.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

B="\033[1m"
C="\033[36m"
G="\033[32m"
Y="\033[33m"
D="\033[2m"
N="\033[0m"

echo ""
echo -e "${B}${C}  Safe Agentic AI — First Time Setup${N}"
echo -e "  ====================================="
echo ""

# ─── Detect platform ────────────────────────────────────────────────────────
case "$(uname -s)" in
  Darwin*)  PLATFORM="macos" ;;
  MINGW*|MSYS*|CYGWIN*) PLATFORM="windows" ;;
  Linux*)   PLATFORM="linux" ;;
  *)        PLATFORM="linux" ;;
esac

echo -e "  Platform detected: ${G}${PLATFORM}${N}"
echo ""

# ─── Platform-specific defaults ─────────────────────────────────────────────
WORKSPACE_DEFAULT="$HOME/GIT"
SSH_PATH_DEFAULT="$HOME/.ssh"
CLAUDE_PATH_DEFAULT="$HOME/.claude"

case "$PLATFORM" in
  macos)
    MEMORY_DEFAULT="4G"
    CPUS_DEFAULT="4"
    ;;
  windows)
    MEMORY_DEFAULT="8G"
    CPUS_DEFAULT="4"
    ;;
  linux)
    MEMORY_DEFAULT="4G"
    CPUS_DEFAULT="4"
    ;;
esac

# ─── Git identity ──────────────────────────────────────────────────────────
echo -e "${B}  Git Identity${N} (used for commits inside the container)"
read -rp "  Your name: " GIT_NAME
read -rp "  Your email: " GIT_EMAIL
echo ""

# ─── Paths ──────────────────────────────────────────────────────────────────
echo -e "${B}  Paths${N} (press Enter for defaults)"
read -rp "  Workspace folder [$WORKSPACE_DEFAULT]: " WORKSPACE_INPUT
WORKSPACE="${WORKSPACE_INPUT:-$WORKSPACE_DEFAULT}"

read -rp "  SSH keys folder [$SSH_PATH_DEFAULT]: " SSH_INPUT
SSH_PATH="${SSH_INPUT:-$SSH_PATH_DEFAULT}"

read -rp "  Claude config folder [$CLAUDE_PATH_DEFAULT]: " CLAUDE_INPUT
CLAUDE_PATH="${CLAUDE_INPUT:-$CLAUDE_PATH_DEFAULT}"
echo ""

# ─── SSH Agent Provider ────────────────────────────────────────────────────
echo -e "${B}  SSH Agent${N}"
echo ""
echo "  Which SSH agent do you use?"
echo -e "    ${C}1)${N} 1Password"
echo -e "    ${C}2)${N} Keeper PAM"
echo -e "    ${C}3)${N} Custom (other SSH agent)"
echo -e "    ${C}4)${N} None / skip"
echo ""
read -rp "  Choice [1]: " AGENT_CHOICE
AGENT_CHOICE="${AGENT_CHOICE:-1}"

SSH_SOCK=""
AGENT_PROVIDER="none"

case "$AGENT_CHOICE" in
  1)
    AGENT_PROVIDER="1password"
    case "$PLATFORM" in
      macos)
        SSH_SOCK_DEFAULT="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
        ;;
      windows)
        SSH_SOCK_DEFAULT="/run/host-services/ssh-auth.sock"
        ;;
      linux)
        SSH_SOCK_DEFAULT="$HOME/.1password/agent.sock"
        ;;
    esac
    read -rp "  1Password socket [$SSH_SOCK_DEFAULT]: " SSH_SOCK_INPUT
    SSH_SOCK="${SSH_SOCK_INPUT:-$SSH_SOCK_DEFAULT}"
    ;;
  2)
    AGENT_PROVIDER="keeper"
    echo ""
    echo -e "  ${D}Keeper PAM uses email-based socket: ~/.keeper/<email>.ssh_agent${N}"
    echo -e "  ${D}Start the agent first: keeper ssh-agent start${N}"
    echo -e "  ${D}Docs: https://docs.keeper.io/en/keeperpam/commander-cli/command-reference/connection-commands/ssh-agent${N}"
    echo ""
    read -rp "  Your Keeper account email: " KEEPER_EMAIL
    if [ -n "$KEEPER_EMAIL" ]; then
      SSH_SOCK_DEFAULT="$HOME/.keeper/${KEEPER_EMAIL}.ssh_agent"
    else
      SSH_SOCK_DEFAULT=""
    fi
    read -rp "  Keeper socket [$SSH_SOCK_DEFAULT]: " SSH_SOCK_INPUT
    SSH_SOCK="${SSH_SOCK_INPUT:-$SSH_SOCK_DEFAULT}"
    ;;
  3)
    AGENT_PROVIDER="custom"
    echo ""
    read -rp "  SSH agent socket path: " SSH_SOCK
    ;;
  4)
    AGENT_PROVIDER="none"
    SSH_SOCK=""
    echo -e "  ${Y}Skipping SSH agent setup.${N}"
    ;;
esac
echo ""

# ─── Resources ──────────────────────────────────────────────────────────────
echo -e "${B}  Resources${N}"
read -rp "  Workspace memory [$MEMORY_DEFAULT]: " MEM_INPUT
MEMORY="${MEM_INPUT:-$MEMORY_DEFAULT}"
read -rp "  Workspace CPUs [$CPUS_DEFAULT]: " CPU_INPUT
CPUS="${CPU_INPUT:-$CPUS_DEFAULT}"
echo ""

# ─── Git signing ────────────────────────────────────────────────────────────
echo -e "${B}  Git Signing Key${N} (optional — path inside container)"
echo "  Leave empty to skip commit signing."
read -rp "  SSH signing key []: " SIGNING_KEY
echo ""

# ─── Generate .env ──────────────────────────────────────────────────────────
cat > .env << ENVEOF
# Generated by setup.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Platform: $PLATFORM

PLATFORM=$PLATFORM

# Git
GIT_USER_NAME=$GIT_NAME
GIT_USER_EMAIL=$GIT_EMAIL

# SSH Agent
SSH_AGENT_PROVIDER=$AGENT_PROVIDER
SSH_AGENT_SOCK_HOST=$SSH_SOCK

# Paths
WORKSPACE_PATH=$WORKSPACE
SSH_HOST_PATH=$SSH_PATH
CLAUDE_CONFIG_PATH=$CLAUDE_PATH

# Resources
WORKSPACE_MEMORY=$MEMORY
WORKSPACE_CPUS=$CPUS
PROXY_MEMORY=256M
PROXY_CPUS=1
TMP_SIZE=536870912

# Git signing (optional)
SSH_SIGNING_KEY=$SIGNING_KEY

# Claude overrides (uncomment if needed)
# ANTHROPIC_API_KEY=sk-ant-xxxxxxxxxxxxx
# CLAUDE_MODEL=claude-opus-4-20250514
# CLAUDE_MAX_TURNS=25
ENVEOF

echo -e "${G}  .env created successfully!${N}"
echo ""

# ─── Create workspace directory if needed ────────────────────────────────────
if [ ! -d "$WORKSPACE" ]; then
  read -rp "  Workspace $WORKSPACE doesn't exist. Create it? [Y/n]: " CREATE_WS
  if [ "${CREATE_WS:-Y}" != "n" ]; then
    mkdir -p "$WORKSPACE"
    echo -e "  ${G}Created $WORKSPACE${N}"
  fi
fi

# ─── Make scripts executable ────────────────────────────────────────────────
chmod +x scripts/*.sh 2>/dev/null || true

# ─── Next steps ──────────────────────────────────────────────────────────────
echo ""
echo -e "${B}  Next steps:${N}"
echo ""
echo "  1. Open this folder in VS Code:"
echo "     code ."
echo ""
echo "  2. Reopen in container:"
echo "     Cmd+Shift+P (macOS) / Ctrl+Shift+P (Windows)"
echo "     -> 'Dev Containers: Reopen in Container'"
echo ""
echo "  3. Inside the container, run:"
echo "     ccd              # interactive Claude (dangerous mode — safe in container)"
echo "     ccw              # watchdog mode (auto-restart)"
echo "     cch \"your task\"  # headless autonomous agent"
echo ""
echo -e "${C}  Happy prompting!${N}"
echo ""
